// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClimberClimb.h"
#include "Commands/ClimberClimbSequence.h"
#include "Commands/ClimberPause.h"
#include "Commands/ClimberTimedClimb.h"
#include "Commands/DriveTrainManualControl.h"
#include "Commands/DriveTrainPause.h"
#include "Commands/DriveTrainTimedMoveBackward.h"
#include "Commands/DriveTrainTimedMoveForward.h"
#include "Commands/FloorGearDeployPickup.h"
#include "Commands/FloorGearPause.h"
#include "Commands/FloorGearRetractPickup.h"
#include "Commands/FloorGearTogglePickup.h"
#include "Commands/StationGearCloseFlap.h"
#include "Commands/StationGearCloseVent.h"
#include "Commands/StationGearDeployGearHolder.h"
#include "Commands/StationGearOpenFlap.h"
#include "Commands/StationGearOpenVent.h"
#include "Commands/StationGearPause.h"
#include "Commands/StationGearRetractGearHolder.h"
#include "Commands/StationGearToggleFlap.h"
#include "Commands/TansmissionUpShift.h"
#include "Commands/TransmissionDownShift.h"
#include "Commands/TransmissionToggleShift.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <iostream>


OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    theDriver.reset(new XboxController(2));
    
    theOperator.reset(new XboxController(1));
    

    // SmartDashboard Buttons
    SmartDashboard::PutData("ClimberClimb", new ClimberClimb());
    SmartDashboard::PutData("FloorGearTogglePickup", new FloorGearTogglePickup());
    SmartDashboard::PutData("FloorGearRetractPickup", new FloorGearRetractPickup());
    SmartDashboard::PutData("FloorGearDeployPickup", new FloorGearDeployPickup());
    SmartDashboard::PutData("StationGearToggleFlap", new StationGearToggleFlap());
    SmartDashboard::PutData("StationGearCloseFlap", new StationGearCloseFlap());
    SmartDashboard::PutData("StationGearOpenFlap", new StationGearOpenFlap());
    SmartDashboard::PutData("StationGearRetractGearHolder", new StationGearRetractGearHolder());
    SmartDashboard::PutData("StationGearDeployGearHolder", new StationGearDeployGearHolder());
    SmartDashboard::PutData("StationGearCloseVent", new StationGearCloseVent());
    SmartDashboard::PutData("StationGearOpenVent", new StationGearOpenVent());
    SmartDashboard::PutData("TransmissionToggleShift", new TransmissionToggleShift());
    SmartDashboard::PutData("TransmissionDownShift", new TransmissionDownShift());
    SmartDashboard::PutData("TansmissionUpShift", new TansmissionUpShift());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	deadzone_x = 0;
	deadzone_y = 0;
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<XboxController> OI::gettheOperator() {
   return theOperator;
}

std::shared_ptr<XboxController> OI::gettheDriver() {
   return theDriver;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

double OI::Get_Driver_X(GenericHID::JoystickHand hand)
{
	double x = theDriver->GetX(hand);
	if (fabs(x) < deadzone_x) return 0;
}

double OI::Get_Driver_Y(GenericHID::JoystickHand hand)
{
	double y = theDriver->GetY(hand);
	if (fabs(y) < deadzone_y) return 0;
}

void OI::Set_Deadzone(double x, double y)
{
	x = fabs(x);
	y = fabs(y);

	if (x >= 1.0)
	{
		std::cout << "ERROR: Invalid Value For Deadzone X! " << x << std::endl << std::flush;
		return;
	}

	if (y >= 1.0)
	{
		std::cout << "ERROR: Invalid Value For Deadzone Y! " << y << std::endl << std::flush;
		return;
	}

	deadzone_x = x;
	deadzone_y = y;
}

