// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "XboxController.h"
#include "GenericHID.h"

using frc;

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<XboxController> theDriver;
	std::shared_ptr<XboxController> theOperator;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	double deadzone_x, deadzone_y;

public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<XboxController> gettheOperator();
	std::shared_ptr<XboxController> gettheDriver();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	double Get_Driver_X(GenericHID::JoystickHand hand);
	double Get_Driver_Y(GenericHID::JoystickHand hand);

	void Set_Deadzone(double x, double y);

};

#endif
